openapi: 3.1.0
info:
  version: ""
  title: Media Gateway RESTful API
  description: >-
    Media Gateway RESTful APIs provide server-side control for RTMP and SRT ingress streams. Use
    these APIs to create and manage streaming keys, query online stream sessions, disconnect or mute
    streams, manage flow configuration templates, and query message notification server IP
    addresses.


    ## API basics


    Most requests are sent to `https://api.agora.io`. The mute or unmute streaming API uses
    `https://api.sd-rtn.com` as its host.


    All request URLs and request bodies are case-sensitive. Keep Media Gateway RESTful API calls on
    your business server.
servers:
  - url: https://api.agora.io
    description: Media Gateway REST API host.
security:
  - basicAuth: []
  - hmacAuth: []
paths:
  /{region}/v1/projects/{appId}/rtls/ingress/streamkeys:
    post:
      summary: Create streaming key
      description: Creates a streaming key for Media Gateway ingress streaming.
      operationId: create-media-gateway-streaming-key
      x-codeSamples:
        - lang: bash
          label: curl
          source: |-
            curl --request POST \
              --url https://api.sd-rtn.com/region/v1/projects/yourActualAppId/rtls/ingress/streamkeys \
              --header 'Accept: application/json' \
              --header 'Authorization: Basic <Base64EncodedCredentials>' \
              --header 'Content-Type: application/json' \
              --header 'X-Request-ID: <UniqueRequestID>' \
              --data '{
              "settings": {
                "channel": "shx001",
                "uid": "1001",
                "expiresAfter": 0
              }
            }'
      x-docs-callouts:
        - markdown: Keep the created streaming key secure to prevent unauthorized streaming to the channel.
          position: after-description
          title: Important
          type: warning
      parameters:
        - $ref: "#/components/parameters/region"
        - $ref: "#/components/parameters/appId"
        - $ref: "#/components/parameters/X-Request-ID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/create-streaming-key-request"
            example:
              settings:
                channel: shx001
                uid: "1001"
                expiresAfter: 0
      responses:
        "200":
          description: The request succeeded and returned the created streaming key.
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/streaming-key-response"
              example:
                status: success
                data:
                  streamKey: 2dfMTR****fys
                  channel: shx001
                  uid: "1001"
                  expiresAfter: 0
                  createdAt: "1686820170"
        "401":
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-docs-sections:
        - position: after-description
          markdown: >-
            Create a key before streaming to ensure that the media stream is pushed to the correct
            channel and under the correct host ID.
  /{region}/v1/projects/{appId}/rtls/ingress/streamkeys/{streamkey}:
    get:
      summary: Query streaming key
      description: Queries information for a specified Media Gateway streaming key.
      operationId: query-media-gateway-streaming-key
      x-codeSamples:
        - lang: bash
          label: curl
          source: >-
            curl --location
            'https://api.agora.io/ap/v1/projects/9d2498880e934632b38b0a68fa2f1622/rtls/ingress/streamkeys/:streamkey

            '
      parameters:
        - $ref: "#/components/parameters/region"
        - $ref: "#/components/parameters/appId"
        - $ref: "#/components/parameters/streamkey"
        - $ref: "#/components/parameters/X-Request-ID"
      responses:
        "200":
          description: The request succeeded and returned streaming key information.
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/streaming-key-response"
              example:
                status: success
                data:
                  streamKey: 2dfMTR****fys
                  channel: shx001
                  uid: "1001"
                  expiresAfter: 0
                  createdAt: "1686820170"
        "401":
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-docs-sections:
        - position: after-description
          markdown: >-
            This method queries the current list of ongoing Media Gateway streams, including the
            associated UID, channel name, stream status, bitrate, and audio and video metrics.
    delete:
      summary: Delete streaming key
      description: Deletes a Media Gateway streaming key.
      operationId: delete-media-gateway-streaming-key
      x-codeSamples:
        - lang: bash
          label: curl
          source: >-
            curl --location -g --request DELETE
            'https://api.agora.io/{{region}}/v1/projects/{{appId}}/rtls/ingress/streamkeys/{{streamKey}}'
      parameters:
        - $ref: "#/components/parameters/region"
        - $ref: "#/components/parameters/appId"
        - $ref: "#/components/parameters/streamkey"
        - $ref: "#/components/parameters/X-Request-ID"
      responses:
        "200":
          description: The request succeeded and deleted the streaming key.
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status-response"
              example:
                status: success
        "401":
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-docs-sections:
        - position: after-description
          markdown: >-
            Call to delete unused streaming keys. After a streaming key is deleted, you can no
            longer use it to push streams. If the deleted streaming key is still in use, the ongoing
            stream is not affected. To disable the ongoing stream immediately, use the SID to [force
            a disconnection](/en/api-reference/api-ref/rtmp-gateway/force-disconnection).


            This API can also be used to revoke streaming keys generated by a script. For a complete
            key revocation, make sure to call this API across all configured regions.
  /{region}/v1/projects/{appId}/rtls/ingress/online-streams:
    get:
      summary: Query streaming list
      description: Queries current Media Gateway ingress streams.
      operationId: query-media-gateway-streaming-list
      x-docs-callouts:
        - type: info
          title: Note
          position: after-description
          markdown: >
            If you specify a channel, the response only contains streams in that channel. Because
            Agora channel names support special characters, URL-encode the channel name before
            sending the request.
      x-codeSamples:
        - lang: bash
          label: curl
          source: |-
            curl --request GET \
              --url https://api.agora.io/region/v1/projects/appId/rtls/ingress/online-streams \
              --header 'Accept: application/json' \
              --header 'Authorization: Basic 123' \
              --header 'X-Request-ID: '
      parameters:
        - $ref: "#/components/parameters/region"
        - $ref: "#/components/parameters/appId"
        - $ref: "#/components/parameters/channel"
        - $ref: "#/components/parameters/X-Request-ID"
      responses:
        "200":
          description: The request succeeded and returned the streaming list.
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/online-stream-list-response"
              example:
                status: success
                data:
                  - sid: string
                    channel: string
                    uid: string
                    url: string
                    status: Running
                    beginAt: "2024-01-01 01:01:01.001"
                    bitrate: 0
                    video:
                      width: 0
                      height: 0
                      fps: 0
                    audio:
                      channels: 0
                      sampleRate: 0
        "401":
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-docs-sections:
        - position: after-description
          markdown: >-
            This method queries the current list of ongoing Media Gateway streams, including the
            associated UID, channel name, stream status, bitrate, and audio and video metrics.
  /{region}/v1/projects/{appId}/rtls/ingress/online-streams/{sid}:
    get:
      summary: Query streaming information
      description: Queries an ongoing Media Gateway stream by SID.
      operationId: query-media-gateway-streaming-information
      x-docs-callouts:
        - type: info
          title: Note
          position: after-description
          markdown: >
            A streaming session ID is generated for each initiated streaming task. You can obtain
            the SID by querying the streaming list or by receiving the message notification
            callback.
      x-codeSamples:
        - lang: bash
          label: curl
          source: |-
            curl --request GET \
              --url https://api.agora.io/region/v1/projects/appId/rtls/ingress/online-streams/sid \
              --header 'Accept: application/json' \
              --header 'Authorization: Basic 123' \
              --header 'X-Request-ID: '
      parameters:
        - $ref: "#/components/parameters/region"
        - $ref: "#/components/parameters/appId"
        - $ref: "#/components/parameters/sid"
        - $ref: "#/components/parameters/X-Request-ID"
      responses:
        "200":
          description: The request succeeded and returned stream information.
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/online-stream-response"
              example:
                status: success
                data:
                  - sid: string
                    channel: string
                    uid: string
                    url: string
                    status: Running
                    beginAt: string
                    bitrate: 0
                    video:
                      width: 0
                      height: 0
                      fps: 0
                    audio:
                      channels: 0
                      sampleRate: 0
        "401":
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-docs-sections:
        - position: after-description
          markdown: This method queries an ongoing push based on SID.
    delete:
      summary: Force disconnect
      description: Disconnects an ongoing Media Gateway stream by SID.
      operationId: force-disconnect-media-gateway-stream
      x-codeSamples:
        - lang: bash
          label: curl
          source: |-
            curl --request DELETE \
              --url https://api.agora.io/region/v1/projects/appId/rtls/ingress/online-streams/sid \
              --header 'Accept: application/json' \
              --header 'Authorization: Basic 123' \
              --header 'X-Request-ID: '
      x-docs-callouts:
        - markdown: >-
            Make sure to delete the streaming key first; otherwise, after using this API to force a
            disconnection, the push software will immediately reconnect. A new push session,
            corresponding to a new SID, will be generated, and the disconnection will fail.
          position: after-description
          title: Important
          type: warning
      parameters:
        - $ref: "#/components/parameters/region"
        - $ref: "#/components/parameters/appId"
        - $ref: "#/components/parameters/sid"
        - $ref: "#/components/parameters/X-Request-ID"
      responses:
        "200":
          description: The request succeeded and sent the disconnection command.
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status-response"
              example:
                status: success
        "401":
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-docs-sections:
        - position: after-description
          markdown: >-
            You can combine this method with [deleting the streaming
            key](/en/api-reference/api-ref/rtmp-gateway/delete-streaming-key) to implement the function of disabling the
            stream. Deleting the streaming key only removes it from the database. You can no longer
            use the streaming key, but you cannot disconnect the ongoing push. To disconnect, use
            one of the following methods:


            1. Call to [delete the streaming key](/en/api-reference/api-ref/rtmp-gateway/delete-streaming-key) and then
            call this method to disconnect the ongoing push.

            2. Call to [kick the user out of the
            channel](/en/api-reference/api-ref/rtc/ban-user-privileges-best-practices#kick-a-user-out-of-a-channel). This API can also force
            the user to disconnect. If the kicking API has been integrated, you can continue to use
            it to disconnect the stream.
  /{region}/{version}/projects/{appId}/rtls/ingress/online-streams/mute/{sid}:
    servers:
      - url: https://api.sd-rtn.com
        description: Media Gateway stream control host.
    post:
      summary: Mute or unmute streaming
      description: Mutes or unmutes the audio of a current Media Gateway stream.
      operationId: mute-media-gateway-stream
      x-codeSamples:
        - lang: bash
          label: curl
          source: |-
            curl --request post \
              --url https://api.sd-rtn.com/:region/:version/projects/:appId/rtls/ingress/online-streams/mute/:sid \
              --header 'Authorization: Basic <credentials>' \
              --header 'X-Request-ID: <string>' \
              --data '
            {
              "settings": {
                "videoMuted": true,
                "audioMuted": false
              }
            }'
      x-docs-callouts:
        - type: info
          title: Note
          position: after-responses
          markdown: >
            - The successful execution of this request only confirms that the command is sent to the
            gateway node handling the stream; it does not guarantee that the mute/unmute operation
            was successful. The operation is executed asynchronously in the background.


            - Typically, the mute/unmute action takes effect within approximately one second. If the
            operation does not work as expected, retry the API call.


            - By default, each stream starts unmuted (audio and video are published normally). Each
            API call applies to the current stream. If the streamer disconnects and restarts the
            stream, the new stream resets to the initial unmuted state.
      parameters:
        - $ref: "#/components/parameters/region"
        - $ref: "#/components/parameters/version"
        - $ref: "#/components/parameters/appId"
        - $ref: "#/components/parameters/sid"
        - $ref: "#/components/parameters/X-Request-ID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/mute-stream-request"
            example:
              settings:
                videoMuted: true
                audioMuted: false
      responses:
        "200":
          description: The request succeeded and sent the mute/unmute command.
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status-response"
              example:
                status: success
        "401":
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-docs-sections:
        - position: after-description
          markdown: Use this method to mute or unmute the current streaming.
  /{region}/v1/projects/{appId}/rtls/ingress/stream-templates/{templateId}:
    put:
      summary: Create or reset template
      description: Creates or resets a Media Gateway flow configuration template.
      operationId: create-or-reset-media-gateway-template
      x-codeSamples:
        - lang: bash
          label: curl
          source: >-
            curl --location -g --request PUT
            'https://api.agora.io/{{region}}/v1/projects/{{appId}}/rtls/ingress/stream-templates/{{templateId}}'
            \

            --data '{
                "settings": {
                    "transcoding": {
                        "video": {
                            "enabled": true,
                            "codec": "H.264",
                            "width": 1280,
                            "height": 720,
                            "fps": 24,
                            "bitrate": 2200,
                            "simulcastStream": {
                                "width": 960,
                                "height": 540,
                                "fps": 24,
                                "bitrate": 1670
                    }
                        },
                        "audio": {
                            "enabled": false,
                            "profile": 3
                        }
                    },
                    "jitterBuffer": {
                        "size": 500,
                        "maxSize": 800
                    }
                }
            }'
      x-docs-callouts:
        - markdown: >-
            By default, a template is not set for the app ID. That is, video transcoding is not
            enabled.
          position: after-description
          title: Note
          type: info
      parameters:
        - $ref: "#/components/parameters/region"
        - $ref: "#/components/parameters/appId"
        - $ref: "#/components/parameters/templateId"
        - $ref: "#/components/parameters/X-Request-ID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/template-settings-request"
            example:
              settings:
                transcoding:
                  video:
                    enabled: true
                    codec: H.264
                    width: 1280
                    height: 720
                    fps: 24
                    bitrate: 2200
                    simulcastStream:
                      width: 960
                      height: 540
                      fps: 24
                      bitrate: 1670
                  audio:
                    enabled: false
                    profile: 3
                jitterBuffer:
                  size: 500
                  maxSize: 800
      responses:
        "200":
          description: The request succeeded and created or reset the template.
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status-response"
              example:
                status: success
        "401":
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-docs-sections:
        - position: after-description
          markdown: >-
            In the template, you can configure transcoding parameters for video or audio streams, as
            well as parameters for mitigating network latency.


            Up to 10 flow configuration templates can be created under an app ID, each with a unique
            `templateId`. Specify the `templateId` when creating a template; if a template
            corresponding to this ID already exists, the existing template will be reset with the
            incoming body data.


            There are two ways to use flow configuration templates, which can be used in
            combination:


            - Specify a global template for the app ID: All streaming keys under the app ID will use
            this template by default.

            - Specify a configuration template for a specific streaming key: When using this key to
            push streams, the specific template will be used.
    patch:
      summary: Update template
      description: Updates an existing Media Gateway flow configuration template.
      operationId: update-media-gateway-template
      x-codeSamples:
        - lang: bash
          label: curl
          source: >-
            curl --location -g --request PUT
            'https://api.agora.io/{{region}}/v1/projects/{{appId}}/rtls/ingress/stream-templates/{{templateId}}'
            \

            --data '

            {
                "settings": {
                    "transcoding": {
                        "video": {
                            "enabled": true,
                            "codec": "H.264",
                            "width": 1280,
                            "height": 720,
                            "fps": 24,
                            "bitrate": 2200,
                            "simulcastStream": {
                                "width": 960,
                                "height": 540,
                                "fps": 24,
                                "bitrate": 1670
                            }
                        }
                    }
                }
            }'
      x-docs-callouts:
        - type: info
          title: Note
          position: after-description
          markdown: >
            - The parameters supported for the update are the following: `transcoding.video`,
            `transcoding.audio`, and `jitterBuffer`. This means that, for example, if you only want
            to update the `fps` field of `transcoding.video`, you need to pass in the entire
            `transcoding.video` field with the modified `fps` field and other fields unchanged.

            - `transcoding.video`, `transcoding.audio`, and `jitterBuffer` are independent of each
            other. If only `transcoding.video` is passed in, then only its parameters will be
            updated and the parameters of `transcoding.audio` and `jitterBuffer` will not be
            affected.
        - markdown: >-
            - This interface can only be called if the flow configuration template already exists.

            - Modifications to a flow configuration template will only take effect after the stream
            is re-pushed. Considering the synchronization delay between the gateway and the
            database, wait 3 minutes after calling this interface before re-pushing the stream.
          position: after-description
          title: Note
          type: info
      parameters:
        - $ref: "#/components/parameters/region"
        - $ref: "#/components/parameters/appId"
        - $ref: "#/components/parameters/templateId"
        - $ref: "#/components/parameters/X-Request-ID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/template-settings-request"
            example:
              settings:
                transcoding:
                  video:
                    enabled: true
                    codec: H.264
                    width: 1280
                    height: 720
                    fps: 24
                    bitrate: 2200
                    simulcastStream:
                      width: 960
                      height: 540
                      fps: 24
                      bitrate: 1670
      responses:
        "200":
          description: The request succeeded and updated the template.
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status-response"
              example:
                status: success
        "401":
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-docs-sections:
        - position: after-description
          markdown: This method updates a flow configuration template.
    delete:
      summary: Delete template
      description: Deletes a Media Gateway flow configuration template.
      operationId: delete-media-gateway-template
      x-docs-callouts:
        - type: info
          title: Note
          position: after-responses
          markdown: >
            For a `401 (Unauthorized)` response, the response header does not include
            `X-Request-ID`.
        - markdown: >-
            - After deletion, the stream currently being pushed using the template will not be
            affected and will still be pushed according to the template parameters. Deletion will
            take effect from the next push, including normal push and disconnection/reconnection).

            - If the template associated with the streaming key is deleted, the global template
            under the app ID will be used by default. If no global template is configured, streaming
            will be performed according to the no-template setting, that is, video transcoding will
            not be enabled.
          position: after-description
          title: Note
          type: info
      parameters:
        - $ref: "#/components/parameters/region"
        - $ref: "#/components/parameters/appId"
        - $ref: "#/components/parameters/templateId"
        - $ref: "#/components/parameters/X-Request-ID"
      x-codeSamples:
        - lang: bash
          label: curl
          source: >-
            curl --location -g --request DELETE
            'https://api.agora.io/{{region}}/v1/projects/{{appId}}/rtls/ingress/stream-templates/{{templateId}}'
      x-docs-sections:
        - position: after-description
          markdown: This method deletes a flow configuration template.
        - position: after-response-body
          markdown: >
            For details about possible response status codes, see [Response status
            codes](/en/api-reference/api-ref/rtmp-gateway/response-status-codes).


            If the status code is not `200`, the request fails. See the `message` field in the
            response body for the reason for this failure.


            If the status code is `200`, the request succeeds, and the response body includes the
            following parameters:
        - position: after-response-example
          title: Response example
          markdown: |
            The following is a response example for a successful request:
        - position: after-response-example
          type: callout
          variant: info
          title: Info
          markdown: >
            To explore the RESTful API parameters, obtain sample code in various client languages,
            or test Media Gateway requests, refer to the [Postman API
            reference](https://documenter.getpostman.com/view/6319646/SVSLr9AM#6aed9690-285e-45f0-a329-c995adbd0956).
      responses:
        "200":
          description: The request succeeded and deleted the template.
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status-response"
              example:
                status: success
        "401":
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
  /{region}/v1/projects/{appId}/rtls/ingress/appconfig:
    put:
      summary: Set global template
      description: Sets a global Media Gateway flow configuration template.
      operationId: set-media-gateway-global-template
      x-codeSamples:
        - lang: bash
          label: curl
          source: >-
            curl --location -g --request PUT
            'https://api.agora.io/{{region}}/v1/projects/{{appId}}/rtls/ingress/appconfig' \

            --data '{
                "settings": {
                    "defaultStreamTemplate": "720p"
                }
            }'
      x-docs-callouts:
        - type: info
          title: Note
          position: after-description
          markdown: >
            For users of the beta version: Previously this API could also be used to set the
            transcoding parameters. Now it is recommended that you use the [template creation
            API](create-reset-template) instead. If you have used this API to set `transcoding`, the
            current flow is the following:

            - If you reset `defaultStreamTemplate`, the  `transcoding` previously set through this
            API will automatically become invalid, and the parameters in the new template will
            prevail.

            - If you do not reset `defaultStreamTemplate`, the `transcoding` previously set through
            this API will remain as the default global configuration for this app ID.
        - markdown: Before calling this API, [create a flow configuration template](create-reset-template).
          position: after-description
          title: Note
          type: info
      parameters:
        - $ref: "#/components/parameters/region"
        - $ref: "#/components/parameters/appId"
        - $ref: "#/components/parameters/X-Request-ID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/global-template-request"
            example:
              settings:
                defaultStreamTemplate: 720p
      responses:
        "200":
          description: The request succeeded and set the global template.
          headers:
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status-response"
              example:
                status: success
        "401":
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-docs-sections:
        - position: after-description
          markdown: >-
            This method sets a global flow configuration template, that is, the template that
            applies to all streaming keys under the app ID.
  /v2/ncs/ip:
    get:
      summary: Query notification service IP address
      description: Retrieves Agora message notification service IP addresses.
      operationId: query-media-gateway-ncs-ip
      x-docs-callouts:
        - type: info
          title: Note
          position: after-description
          markdown: >
            If your server is behind a firewall, configure your firewall to trust the returned IP
            addresses. Agora adjusts message notification service IP addresses every 24 hours. Best
            practice is to call this endpoint at least every 24 hours and automatically update the
            firewall configuration.
      responses:
        "200":
          description: The request succeeded and returned notification service IP addresses.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ncs-ip-response"
              example:
                data:
                  service:
                    hosts:
                      - primaryIP: string
        default:
          $ref: "#/components/responses/error"
      x-docs-sections:
        - position: after-description
          markdown: >-
            When using Agora real-time audio and video, you can use the Agora Notifications service
            to receive channel events.


            After activating the service, when a channel event occurs, the Agora Notifications
            service server will deliver the event notification to your message receiving server.


            If your server is behind a firewall, you need to call the IP address query API to
            retrieve the IP addresses of Agora Notifications service and configure your firewall to
            trust all these IP addresses.


            Agora adjusts the Agora Notifications service IP addresses every 24 hours. Best practice
            is to call this endpoint at least every 24 hours and automatically update the firewall
            configuration.


            * Method: `GET`

            * Endpoint: `https://api.agora.io/v2/ncs/ip`
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: >-
        Basic HTTP authentication. Send an `Authorization` header that contains `Basic` followed by
        a base64-encoded `username:password` string.
    hmacAuth:
      type: apiKey
      in: header
      name: Authorization
      description: HMAC HTTP authentication. Send the generated API key in the `Authorization` request header.
  headers:
    X-Request-ID:
      description: >-
        The UUID (Universally Unique Identifier) of the request. The value is in the `X-Request-ID`
        response header. If a request error occurs, print the value in the log to troubleshoot the
        problem.
      schema:
        type: string
        example: 6d35d43f-f4c5-4b3a-9df4-8f0d7e1d5f0a
  parameters:
    region:
      name: region
      in: path
      required: true
      schema:
        type: string
        enum:
          - na
          - eu
          - ap
          - cn
      description: >-
        Region for the streaming key or stream. Supported values are `na` for North America, `eu`
        for Europe, `ap` for Asia except mainland China, and `cn` for mainland China.
      x-docs-callouts:
        - type: warning
          title: Important
          markdown: |
            Make sure that:

            - The `region` value is the same as for the input source stream.
            - The domain names for setting the `region` parameter and streaming are the same.
            - The `region` value is in lowercase.
    version:
      name: version
      in: path
      required: true
      schema:
        type: string
        enum:
          - v1
      description: The API version. Use `v1`.
    appId:
      name: appId
      in: path
      required: true
      schema:
        type: string
      description: >-
        The app ID provided by Agora to each developer. After creating a project in Agora Console,
        you can get an app ID. The app ID is a unique identifier for a project.
    streamkey:
      name: streamkey
      in: path
      required: true
      schema:
        type: string
      description: The streaming key.
    sid:
      name: sid
      in: path
      required: true
      schema:
        type: string
      description: The streaming session ID. Each initiated streaming task generates a unique SID.
    templateId:
      name: templateId
      in: path
      required: true
      schema:
        type: string
        maxLength: 12
        pattern: ^[A-Za-z0-9]+$
        example: 720p
      description: >-
        The flow configuration template ID. The value can contain only lowercase letters, uppercase
        letters, and numbers, and cannot exceed 12 bytes. Set the value according to your business
        use case. For example, use `"720p"` and `"1080p"` for different target resolutions, or
        `"gameA"` and `"gameB"` for different game use cases.
    channel:
      name: channel
      in: query
      required: false
      schema:
        type: string
      description: >-
        The channel name. If specified, the response only contains streams in the specified channel.
        URL-encode the channel name before sending the request.
    X-Request-ID:
      name: X-Request-ID
      in: header
      required: false
      schema:
        type: string
        example: 6d35d43f-f4c5-4b3a-9df4-8f0d7e1d5f0a
      description: >-
        The UUID (Universally Unique Identifier) of the request. After you pass in this field, the
        Agora server returns this field in the response header. It is recommended to assign
        `X-Request-ID` a value. If omitted, the Agora server automatically generates a UUID and
        returns it.
  responses:
    error:
      description: >-
        The request failed. A `401 (Unauthorized)` response status code means the request is not
        authorized.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error-response"
          example:
            status: error
            message: Describes why the request failed.
  schemas:
    create-streaming-key-request:
      type: object
      required:
        - settings
      properties:
        settings:
          type: object
          x-docs-callouts:
            - type: warning
              title: Important
              markdown: |
                To ensure a successful request, do not leave this field empty or set to null.
          required:
            - channel
            - uid
            - expiresAfter
          properties:
            channel:
              type: string
              description: >-
                Agora channel name. The string length must be less than 64 bytes. You can leave this
                field empty and Agora uses a random integer UID to enter the channel in the
                `GR-xxxx` format. The `channel` and `uid` parameters cannot be empty or `0` at the
                same time.
            uid:
              type: string
              description: >-
                Host user UID in the Agora channel. Numeric IDs can range from 1 to 4294967295.
                String IDs cannot exceed 255 bytes or be empty. If this field is empty or `0`, Agora
                uses a random integer UID. The `channel` and `uid` parameters cannot be empty or `0`
                at the same time.
            expiresAfter:
              type: integer
              description: >-
                Validity period of the streaming key in seconds from creation. If set to `0`, the
                streaming key is always valid. Do not leave this field empty or set it to null.
            templateId:
              type: string
              description: >-
                Associated flow configuration template ID. Omit this field if you have not created a
                configuration template. If omitted, the default configuration is used.
    streaming-key-response:
      type: object
      properties:
        status:
          type: string
          description: Request status. `success` means the request succeeds.
        data:
          $ref: "#/components/schemas/streaming-key-data"
    streaming-key-data:
      type: object
      properties:
        streamKey:
          type: string
          description: The streaming key.
        channel:
          type: string
          description: Agora channel name associated with the streaming key.
        uid:
          type: string
          description: User UID associated with the streaming key.
        expiresAfter:
          type: integer
          description: Validity period of the streaming key in seconds.
        createdAt:
          type: string
          description: Unix timestamp, in seconds, when the streaming key was created.
    online-stream-list-response:
      type: object
      properties:
        status:
          type: string
          description: Request status. `success` means the request succeeds.
        data:
          type: array
          items:
            $ref: "#/components/schemas/online-stream"
    online-stream-response:
      type: object
      properties:
        status:
          type: string
          description: Request status. `success` means the request succeeds.
        data:
          type: array
          items:
            $ref: "#/components/schemas/online-stream"
    online-stream:
      type: object
      properties:
        sid:
          type: string
          description: Streaming session ID. Each stream has a unique SID.
        channel:
          type: string
          description: Agora channel name associated with the streaming key.
        uid:
          type: string
          description: User UID associated with the streaming key.
        url:
          type: string
          description: Push address in the `$domain/live/$streamkey` format.
        status:
          type: string
          enum:
            - Started
            - Running
          description: >-
            Stream status. `Started` means the connection is established and waiting to stream audio
            and video. `Running` means the stream is being streamed.
        beginAt:
          type: string
          description: Streaming start time in the `2024-01-01 01:01:01.001` format.
        bitrate:
          type: integer
          description: Source stream bitrate, audio plus video, in Kbps.
        video:
          type: object
          description: Video stream parameters returned when the status is `Running`.
          properties:
            width:
              type: integer
              description: Video width in pixels.
            height:
              type: integer
              description: Video height in pixels.
            fps:
              type: integer
              description: Video frame rate in frames per second.
        audio:
          type: object
          description: Audio stream parameters returned when the status is `Running`.
          properties:
            channels:
              type: integer
              description: Number of audio channels.
            sampleRate:
              type: integer
              description: Audio sampling rate in Hz.
    mute-stream-request:
      type: object
      required:
        - settings
      properties:
        settings:
          type: object
          required:
            - videoMuted
            - audioMuted
          properties:
            videoMuted:
              type: boolean
              description: >-
                Whether to mute the video stream. `true` mutes video publishing; `false` unmutes
                video publishing.
            audioMuted:
              type: boolean
              description: >-
                Whether to mute the audio stream. `true` mutes audio publishing; `false` unmutes
                audio publishing.
    template-settings-request:
      type: object
      required:
        - settings
      properties:
        settings:
          $ref: "#/components/schemas/template-settings"
          x-docs-callouts:
            - type: info
              title: Note
              markdown: >
                To ensure a successful request, do not set the required fields to `null` or leave
                them empty.
    template-settings:
      type: object
      required:
        - transcoding
      properties:
        transcoding:
          type: object
          description: Audio and video transcoding configuration.
          properties:
            video:
              $ref: "#/components/schemas/video-transcoding"
            audio:
              $ref: "#/components/schemas/audio-transcoding"
        jitterBuffer:
          $ref: "#/components/schemas/jitter-buffer"
    video-transcoding:
      type: object
      properties:
        enabled:
          type: boolean
          default: false
          description: Whether to enable video transcoding.
        mode:
          type: string
          default: force
          enum:
            - force
            - adaptive
          description: >-
            Video transcoding mode. `force` forces transcoding. `adaptive` enables transcoding when
            the source stream contains B-frames.
        codec:
          type: string
          default: H.264
          enum:
            - H.264
            - VP8
          description: Codec format for transcoding.
        width:
          type: integer
          minimum: 0
          maximum: 3840
          description: >-
            Encoding width of the main stream in pixels. If not specified or set to `0`, the source
            stream width is used unless `height` is set.
          x-docs-callouts:
            - type: info
              title: Note
              markdown: |
                If the ABR function is enabled, this field is required.
        height:
          type: integer
          minimum: 0
          maximum: 3840
          description: >-
            Encoding height of the main stream in pixels. If not specified or set to `0`, the source
            stream height is used unless `width` is set.
          x-docs-callouts:
            - type: info
              title: Note
              markdown: |
                If the ABR function is enabled, this field is required.
        fps:
          type: integer
          minimum: 0
          maximum: 60
          description: >-
            Video encoding frame rate in fps. If not specified or set to `0`, the source stream
            frame rate is used.
        bitrate:
          type: integer
          minimum: 0
          maximum: 20000
          description: >-
            Encoding bitrate of the main stream in Kbps. If omitted, the source stream bitrate is
            used. If set to `0`, Agora automatically chooses a bitrate based on width and height.
          x-docs-callouts:
            - type: info
              title: Note
              markdown: >
                If you enable low-speed streaming (provide the following `simulcastStream` object),
                this field is required. If you do not enable low-speed streaming, it is recommended
                to use the automatically matched bitrate without setting the bitrate yourself.
        advancedOptions:
          type: object
          properties:
            pvc:
              type: object
              properties:
                enabled:
                  type: boolean
                  default: false
                  description: Whether to enable PVC.
                saveBitrateRatio:
                  type: integer
                  description: >-
                    Bitrate saving ratio for PVC. For example, `20` means saving 20 percent of the
                    bitrate. This parameter is effective only when `video.bitrate` is missing or
                    `0`.
            superResolution:
              type: object
              properties:
                enabled:
                  type: boolean
                  default: false
                  description: Whether to enable Super Resolution.
                alphaBlending:
                  type: integer
                  minimum: 1
                  maximum: 256
                  default: 128
                  description: Super Resolution intensity. Larger values indicate higher intensity.
        simulcastStream:
          $ref: "#/components/schemas/simulcast-stream"
        simulcastStreamLayers:
          type: array
          description: Layer transcoding parameters for adaptive bitrate. If specified, ABR is enabled.
          x-docs-callouts:
            - type: info
              title: Note
              markdown: >-
                - You can set either `simulcastStream` or `simulcastStreamLayer`. If you set both,
                `simulcastStream` setting does not take effect.


                - For resolution and bitrate settings for main and ABR streams, recommended values,
                and viewer subscription settings, refer to [Enable adaptive
                bitrate](/en/realtime-media/rtmp-gateway/build/optimize-quality-and-monitor-events/enable-adaptive-bitrate).
          items:
            $ref: "#/components/schemas/simulcast-stream-layer"
    simulcast-stream:
      type: object
      description: >-
        Low-quality video stream configuration. If provided, Media Gateway enables the low-quality
        stream and uses these transcoding parameters.
      properties:
        width:
          type: integer
          minimum: 0
          maximum: 3840
          description: >-
            Width in pixels. The value must be less than `video.width`. If omitted or set to `0`,
            `video.width / 2` is used.
        height:
          type: integer
          minimum: 0
          maximum: 3840
          description: >-
            Height in pixels. The value must be less than `video.height`. If omitted or set to `0`,
            `video.height / 2` is used.
        fps:
          type: integer
          default: 15
          minimum: 0
          maximum: 60
          description: >-
            Frame rate in fps. The value must be less than or equal to `video.fps`. If omitted or
            set to `0`, the default value is `15`.
        bitrate:
          type: integer
          description: >-
            Bitrate of the low-quality video stream in Kbps. The value must be less than
            `video.bitrate`. If omitted or set to `0`, Agora chooses an appropriate bitrate based on
            resolution and fps.
          x-docs-callouts:
            - type: info
              title: Note
              markdown: >
                When enabling the low-quality stream and specifying low-quality `bitrate`, you need
                to specify `video.bitrate` at the same time.
    simulcast-stream-layer:
      type: object
      required:
        - id
        - bitrate
      properties:
        id:
          type: integer
          minimum: 1
          maximum: 7
          description: Layer ID.
        width:
          type: integer
          description: >-
            Encoding width of the layer in pixels. If specified, this value must be smaller than
            `video.width` and decrease monotonically as layer ID increases.
        height:
          type: integer
          description: >-
            Encoding height of the layer in pixels. If specified, this value must be smaller than
            `video.height` and decrease monotonically as layer ID increases.
        fps:
          type: integer
          description: >-
            Encoding frame rate of the layer in fps. If specified, this value must be smaller than
            `video.fps`. If omitted or set to `0`, the main stream frame rate is used.
        bitrate:
          type: integer
          description: >-
            Encoding bitrate of the layer in Kbps. This value must be smaller than `video.bitrate`
            and decrease monotonically by layer ID.
    audio-transcoding:
      type: object
      properties:
        enabled:
          type: boolean
          default: true
          description: Whether to enable audio transcoding.
        profile:
          type: integer
          default: 0
          description: >-
            Encoded audio use case. The default value `0` means 48 KHz sampling rate, music
            encoding, mono, and a maximum encoding rate of 64 Kbps. Contact Agora technical support
            for other profile settings.
        bitrate:
          type: integer
          minimum: 64
          maximum: 320
          description: Audio encoding bitrate in Kbps. If omitted, the value is determined by `profile`.
    jitter-buffer:
      type: object
      description: Network jitter buffer. Takes effect only when video transcoding is enabled.
      properties:
        size:
          type: integer
          default: 500
          description: >-
            Maximum buffer length in ms. Media Gateway adds this value to the end-to-end delay to
            reduce lag caused by network jitter.
        maxSize:
          type: integer
          default: 1000
          description: >-
            Maximum buffer length in ms. This value must be greater than `jitterBuffer.size`. When
            the jitter buffer exceeds this value, Media Gateway enables acceleration until it
            returns to `jitterBuffer.size`.
    global-template-request:
      type: object
      required:
        - settings
      properties:
        settings:
          type: object
          required:
            - defaultStreamTemplate
          properties:
            defaultStreamTemplate:
              type: string
              description: The flow configuration template ID to apply globally.
    status-response:
      type: object
      properties:
        status:
          type: string
          description: The status of this request. `success` means the request succeeds.
    ncs-ip-response:
      type: object
      properties:
        data:
          type: object
          properties:
            service:
              type: object
              properties:
                hosts:
                  type: array
                  items:
                    type: object
                    properties:
                      primaryIP:
                        type: string
                        description: >-
                          IP address of the Agora message notification service server. Add this IP
                          address, or returned IP address list, to your firewall whitelist.
    error-response:
      type: object
      properties:
        status:
          type: string
          description: Request status.
        message:
          type: string
          description: Description of why the request failed.
